import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const MainLayout = ({children, activeFilter, onChangeCategories}) => {

	return (
		<>
			<Head>
        <title>Sequis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sequis.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link href="https://fonts.googleapis.com/css2?family=Labrada:wght@300&family=Ubuntu&display=swap" rel="stylesheet" />
      </Head>

      <div className="container-fluid">
	      <Navbar onChange={onChangeCategories} active={activeFilter} />

	      {children}

	      <div className="row">
          <Footer />
        </div>
      </div>
		</>
	)
}

export default MainLayout