import Head from 'next/head'
import Navbar from '../components/Navbar'

const MainLayout = ({children}) => {
	return (
		<>
			<Head>
        <title>Sequis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sequis.png" />
      </Head>

      <div className="container-fluid">
	      <Navbar />
	      {children}
      </div>
		</>
	)
}

export default MainLayout